Messages = {
	
	// COMMON CONTENT SECTION. KEEPT IT TOP OF MODULE SECTIONS.
	"lbl.name"						:	"ബിജേഷ്‌കുമാർ",
	"lbl.age"						:	"പ്രധാന",
	"lbl.comment"					: 	"അഭിപ്രായം",					
	"login.btn.label" 				: 	"ലോഗിൻ",
	"login.placeholder.passkey" 	: 	"പാസ്കീ",
	"login.failure.message" 		: 	"നിങ്ങൾ തെറ്റായ പാസ്കീ നൽകി",
	"btn.clear"						: 	"ക്ലിയർ",
	"btn.search"					: 	"തിരയൽ",
	"btn.show"						: 	"കാണിക്കുക",
	"btn.addtransaction"			: 	"ഇടപാട് ചേർക്കുക",

	"menu.dashboard"				:	"Dashboard",
	"menu.travel"					:	"Travel",
	"menu.mobile"					:	"Mobile",
	"menu.internet"					:	"Internet",
	"menu.houserent"				:	"House Rent",
	"menu.ksfe"						:	"KSFE",
	"menu.gas"						:	"Gas",
	"menu.carservice"				:	"Car Service",
	"menu.milk"						:	"Milk",
	"menu.eb"						:	"Electricty",
	"menu.passkey-reset"			:	"Reset Passkey",
	"menu.logout"					:	"Logout",
	"menu.medicalbill"				:	"Medicalbill",
	"menu.cart"						:	"Shopping Cart",
	"menu.money"					:	"Money",
	"menu.school"					: 	"School",
	"menu.homeloan"					: 	"Home Loan",
	"menu.flat"						: 	"Flat",
	"menu.carmanager"				: 	"Car Manager",
	"menu.insurance"				: 	"ഇൻഷുറൻസ് മാനേജർ",

	"breadcrumb.dashboard"				:	"Dashboard",
	"breadcrumb.travel"					:	"Travel",
	"breadcrumb.mobile"					:	"Mobile",
	"breadcrumb.internet"				:	"Internet",
	"breadcrumb.houserent"				:	"House Rent",
	"breadcrumb.ksfe"					:	"KSFE",
	"breadcrumb.gas"					:	"Gas",
	"breadcrumb.carservice"				:	"Car Service",
	"breadcrumb.milk"					:	"Milk",
	"breadcrumb.eb"						:	"Electricty",
	"breadcrumb.passkey-reset"			:	"Reset Passkey",
	"breadcrumb.logout"					:	"Logout",
	"breadcrumb.medicalbill"			:	"Medicalbill",
	"breadcrumb.cart"					:	"Shopping Cart",
	"breadcrumb.money"					:	"Money",
	"breadcrumb.flat"					:	"Flat",
	"breadcrumb.insurance"				: 	"Insurance Manager",
	"breadcrumb.insurance.transaction"	: 	"Insurance Transaction",

	"cnt.rent.pageheader"				:	"sdasdas asdasdas asdasdasdasdsadas asdasdasdasdasdasd sadsadsadasdasd asdasdasdasdasdasdasdas  <a href='#/ll/'>Click here to see the list of landlord</a>",
	"cnt.rent.ll.pageheader"			:	"Shows rental details. Click on the landlord name to get the detailed rent view of that particular landlord. Click any of the icons from action coloumn to edit / delete / view the comment. Click on the add icon on the top rightside to add new data.",
	"cnt.rent.ll.details.pageheader"	:	"Shows rental details. Click on the landlord name to get the detailed rent view of that particular landlord. Click any of the icons from action coloumn to edit / delete / view the comment. Click on the add icon on the top rightside to add new data. <a href='#/ll/'>Click here to see the list of landlord</a>",
	"cnt.gas.details.pageheader" 		: 	"Page shows the detailed view of cooking gas consumption. Sub status green is <u>amount transferred to bank account</u>, red is <u>amount not yet transferred to bank account</u>. Order status red is <u>not yet delivered</u> and green is <u>delivered</u>.",
	"cnt.travel.pageheader"				:	"This page shows the details of travel such as booked date, travel date, status of travel, mode of travel etc. Color of icon depicts the status of the travel. Red means Refund, Orange means Pending, Gray means Cancelled or Completed, Green means Open",
	"cnt.dashboard.pageheader"			:	"This page shows the details of travel such as booked date, travel date, status of travel, mode of travel etc. Color of icon depicts the status of the travel. Red means Refund, Orange means Pending, Gray means Cancelled or Completed, Green means Open",
	"cnt.ksfe.pageheader"				:	"It is a unique financial product, which blends the advantages of both investment and advance. It is a risk free safe haven for the public as KSFE conducts only chitties fully governed by the provisions of Central Chit Fund Act 1982",
	"cnt.medicalbill.pageheader"		: 	"Medical bill tax service section.",

	"modal.update.title" 		: 	"updated",
	"modal.update.message"		:	"Data updated successfully!",
	"modal.add.title" 			: 	"added",
	"modal.add.message"			:	"Data added successfully!",

	"cnt.rows"								:	"Record : ",
	"cnt.total"								:  	"Total Amount : ",
	"table.row.header"						:	"records found",

	"tooltip.edit" 			: 	"Edit",
	"tooltip.add" 			: 	"Add",
	"tooltip.trash" 		: 	"Trash",
	"tooltip.comment"		: 	"Comment",
	"tooltip.refresh"		:	"Refresh",

	"setting.language.malayalam"				: 	"Malayalam",
	"setting.language.english"					: 	"English",

	"generalinfo.one" : "Facility is not available at this moment. Visit again later",

	"validation.header"				: 	"Please correct the below listed errors",
// ------------------------------------------------------------------------------------------

	//DASHBOARD SECTION
	"dashboard.pageheader"					:	"Dashboard",
	"dashboard.tbl.contact"					:	"Contact",
	"dashboard.tbl.amount"					:	"Amount",
	"dashboard.tbl.edit"					:	"Edit",
	"dashboard.title.iowe"					:	"I Owe",
	"dashboard.title.iowesme"				:	"Who Owes Me",
	"dashboard.title.billreminders"			:	"Bill Reminders",
	"dashboard.tbl.billitem"				:	"Bill Item",
	"dashboard.tbl.billdate"				:	"Bill Date",
	"dashboard.tbl.totalitem"				:	"Particulars",
	"dashboard.title.mobilechart"			:	"Mobile Chart",
	"dashboard.title.Totals"				:	"Grand Totals",

	"grandtotal.label.rent"					:	"Flat / Appartment Rent",
	"grandtotal.label.mobile"				:	"Mobile bill (husband and wife)",
	"grandtotal.label.gas"					:	"Home Gas (Post Subsidey)",
	"grandtotal.label.net"					:	"Broadband Connection",
	"grandtotal.label.eb"					:	"Electricity Charge",

	"panelsticker.medicalbill"				: 	"Medicalbill",
	"panelsticker.travel"					: 	"Travel",
	"panelsticker.homerent"					: 	"Home Rent",
	"panelsticker.schoolfees"				: 	"School Fees",
	"panelsticker.broadband"				: 	"Internet Connection",
	"panelsticker.mobile"					: 	"Mobile Bill(husband & Wife)",
	"panelsticker.electricity"				: 	"Electricity",
	"panelsticker.gas"						: 	"Home Gas",
	"panelsticker.flatemi"					: 	"Home Loan EMI",
	"panelsticker.loaninsurance"			: 	"Home Loan Insurance EMI",
	"panelsticker.carparking"				: 	"2nd Car Parking",
	"panelsticker.flatmaintenance"			: 	"Flat Maintenance Charge",
	"panelsticker.othercharges"				: 	"Others Charges",
	"panelsticker.fuel"						: 	"Fuel Charges",
	"panelsticker.carservice"				: 	"Service Charges",
	"panelsticker.carinsurance"				: 	"Car Insurance",

	"validation.field.notempty"					:	"Field(s) should not be empty",
	"validation.br.field.item"					:	"Item should not be empty",
	"validation.br.field.amount"				:	"Amount should not be empty",
	"validation.br.field.billdate"				:	"Billdate should not be empty",
	"validation.br.field.status"				:	"Status should not be empty",

	"validation.iowe.field.contact"			:	"To whome should not be empty",
	"validation.iowe.field.amount"			:	"Amount should not be empty",
	"validation.iowe.field.owedate"			:	"I Owe date should not be empty",
	"validation.iowe.field.status"			:	"Status should not be empty",
	"validation.iowe.field.category"		:	"Category should not be empty",

	"br.edit.placeholder.item"			:	"Item",
	"br.edit.placeholder.amount"		:	"Amount",
	"br.edit.placeholder.billdate"		:	"Bill Date",
	"br.edit.placeholder.status"		:	"- Select status -",

	"iowe.edit.placeholder.contact"			:	"To Whome",
	"iowe.edit.placeholder.amount"			:	"Amount",
	"iowe.edit.placeholder.owedate"			:	"I Owe Date",
	"iowe.edit.placeholder.paiddate"		:	"Paid Date",
	"iowe.edit.placeholder.status"			:	"- Select status -",
	"iowe.edit.placeholder.category"		:	"- Select category -",

	"addbr"					:	"Add Bill Reminder",
	"editbr"				:	"Edit Bill Reminder",
	"addrent"				:	"Add Rent Data",
	"addiowe"				:	"Add I Owe Data",
	"editiowe"				:	"Edit I Owe Data",

// TRAVEL MANAGER SECTION
	"travel.pageheader"						:	"Travel Details",
	"travel.breadcrumb" 					: 	"Travel",
	"travel.tbl.icon"						:	"icon",
	"travel.tbl.source"						:	"source",
	"travel.tbl.destination"				:	"Destination",
	"travel.tbl.pnr"						:	"pnr",
	"travel.tbl.traveldate"					:	"travel date",
	"travel.tbl.bookeddate"					:	"booked date",
	"travel.tbl.amount"						:	"amount",
	"travel.tbl.action"						:	"action",
	"cnt.rows"								:	"Record : ",
	"cnt.total"								:  	"Total Amount : ",
	"addtravel"								:	"Add Travel Data",
	"edittravel"							:	"Edit Travel Data",
	"breadcrumbMain"						:	"aswa",
	"table.row.header"						:	"records found",
	"travel.placeholder.travelstatus" 		: 	"Choose travel status",
	"travel.placeholder.travelicon" 		: 	"Choose travel mode",

	"travel.placeholder.travelstatus" 		: 	"Choose travel status",
	"travel.placeholder.travelicon" 		: 	"Choose travel mode",

	"travel.edit.form.confirmation.title"		: 	"Travel edit confirmation check",
	"travel.edit.form.confirmation.body"		: 	"There are some data updated in the CRUD form. Please check it or press YES to close the Wwindow",
	
	"validation.travel.source.required"					: 	"Travel Source should not be Empty",
	"validation.travel.destination.required"			: 	"Travel Destination should not be Empty",
	"validation.travel.traveldate.required"				: 	"Travel Date should not be Empty",
	"validation.travel.bookeddate.required"				: 	"Travel Booked Date should not be Empty",
	"validation.travel.pnr.required"					: 	"Travel PNR should not be Empty",
	"validation.travel.amount.required"					: 	"Travel Amount should not be Empty",
	"validation.travel.icon.required"					: 	"Travel Mode should not be Empty",
	"validation.travel.status.required"					: 	"Travel Status should not be Empty",

// MOBILE MANAGER SECTION
	"mobile.pageheader"					: 	"Mobile Bill",
	"mobile.tbl.icon"					: 	"ICON",
	"mobile.tbl.billmonth"				: 	"Bill Month",
	"mobile.tbl.billno"					: 	"Bill No",
	"mobile.tbl.amount"					: 	"Amount",
	"mobile.tbl.user"					: 	"User",
	"mobile.tbl.action"					: 	"Action",
	"addmobile"							: 	"Add New Mobile Entry",
	"placeholder.mobile.billmonth"		: 	"Bill Month",
	"placeholder.mobile.user"			: 	"User",
	"placeholder.mobile.amount"			: 	"Amount",
	"placeholder.mobile.billno"			: 	"Bill no",

	"validation.mobile.field.month"		: 	"Bill month should not be empty",
	"validation.mobile.field.billno"	: 	"Bill number should not be empty",
	"validation.mobile.field.amount"	: 	"Bill amount should not be empty",
	"validation.mobile.field.user"		: 	"Mobile user should not be empty",
	"validation.mobile.field.comment"	: 	"Comment should not be empty",

// MEDICAL BILL MANAGER SECTION
	"medicalbill.pageheader"						: 	"Medical Bill",
	"medicalbill.tbl.icon"							: 	"ICON",
	"medicalbill.tbl.billmonth"						: 	"Bill Month",
	"medicalbill.tbl.billno"						: 	"Bill No",
	"medicalbill.tbl.billtype"						: 	"Bill Type",
	"medicalbill.tbl.amount"						: 	"Amount",
	"medicalbill.tbl.user"							: 	"User",
	"medicalbill.tbl.action"						: 	"Action",
	"addmedicalbill"								: 	"Add New Medical Bill",
	"editmedicalbill"								: 	"Edit Medical Bill",
	"placeholder.medicalbill.billmonth"				: 	"Bill Month",
	"placeholder.medicalbill.user"					: 	"User",
	"placeholder.medicalbill.amount"				: 	"Amount",
	"placeholder.medicalbill.billno"				: 	"Bill no",
	"placeholder.medicalbill.type"					: 	"Bill Type",
	"placeholder.medicalbill.search.startmonth"		: 	"Start Date",
	"placeholder.medicalbill.search.endmonth"		: 	"End Date",

	"validation.medicalbill.field.month"	: 	"Bill month should not be empty",
	"validation.medicalbill.field.billno"	: 	"Bill number should not be empty",
	"validation.medicalbill.field.amount"	: 	"Bill amount should not be empty",
	"validation.medicalbill.field.user"		: 	"Mobile user should not be empty",
	"validation.medicalbill.field.comment"	: 	"Comment should not be empty",


// RENTAL MANAGER SECTION
	"rent.pageheader"						:	"Rent Details",
	"rent.ll.pageheader"					:	"Land Lord Details",
	"rent.breadcrumb" 						: 	"Rent",
	"rent.ll.breadcrumb" 					: 	"landlord",
	"rent.tbl.icon" 				: 	"icon",
	"rent.tbl.month" 				: 	"month",
	"rent.tbl.amount" 				: 	"amount",
	"rent.tbl.landlord" 			: 	"landlord",
	"rent.tbl.comment" 				: 	"comment",
	"rent.tbl.action" 				: 	"action",
	"rent.tbl.receipt"				:	"Receipt",
	"rent.tbl.tootip.clickhere" 	: 	"Click here for detailed view",
	"rent.placeholder.landlord" 	: 	"Choose Landlord",
	"rent.placeholder.rentstatus" 	: 	"Choose status",
	"rent.placeholder.receipt"		: 	"Choose Receipt Status", 
	"rent.placeholder.status"		: 	"Status",
	"rent.placeholder.lltype" 	: 	"Landlord Type",
	"editrent"						:	"Edit Rent Data",
	"rent.ll.edit.title"			: 	"Edit Landlord",
	"rent.ll.add.title"				: 	"Add Landlord",
	"label.rent.totalAmount"		: 	"Total Amount :",
	"label.rent.dop"				: 	"DOP :",
	"label.rent.contact"			: 	"Contact :",
	"label.rent.address"			: 	"Address :",
	"label.rent.comment"			: 	"Comment :",
	"label.rent.link.renttable"		: 	"Rent Table",
	"label.rent.link.landlord"		: 	"Landlord",
	"label.rent.dov"				: 	"DOV :",
	"label.rent.pan"				: 	"PAN :",
	"label.rent.advance"			: 	"Advance :",
	"validation.ll.field.pan"		: 	"Pan is mandatory",
	"validation.ll.field.dop"		: 	"DOP is mandatory",
	"validation.ll.field.dov"		: 	"DOV is mandatory",
	"validation.ll.field.advance"	: 	"Advance is mandatory",
	"validation.ll.field.name"		: 	"Name is mandatory",
	"validation.ll.field.status"	: 	"Status is mandatory",
	"validation.ll.field.contact"	: 	"Contact is mandatory",
	"validation.ll.field.address"	: 	"Address is mandatory",
	"validation.ll.field.comment"	: 	"Comment is mandatory",

	"placeholder.rent.dop"					: 	"DOP",
	"placeholder.rent.dov"					: 	"DOV",
	"placeholder.rent.pan"					: 	"PAN",
	"placeholder.rent.advanceamount"		: 	"Advance Amount",
	"placeholder.rent.contact"				: 	"Contact",
	"placeholder.rent.name"					: 	"Name",

	"filter.placeholder.filterstatus" 	: "- Select status -",
	"filter.placeholder.landlordname" 	: "- Select landlord -",

	"ksfe.pageheader"					:	"KSFE",
	"ksfe.tbl.month"					:	"Month",
	"ksfe.tbl.amount"					:	"Amount",
	"ksfe.tbl.status"					:	"Status",
	"ksfe.tbl.comment"					:	"Comments",

// GAS MANAGER SECTION
	"gas.pageheader"				:	"Gas Details",
	"gas.breadcrumb" 				: 	"Gas",
	"gas.tbl.bill"					:	"bill",
	"gas.tbl.orderdate"				:	"Order Date",
	"gas.tbl.delivereddate"			:	"Deli-Date",
	"gas.tbl.orderstatus"			:	"status",
	"gas.tbl.amountpaid"			:	"paid",
	"gas.tbl.subamount"				:	"subsidey",
	"gas.tbl.substatus"				:	"sub-status",


// CART MANAGER SECTION
	"cart.pageheader"				: 	"Shopping Cart",
	"cnt.cart.pageheader"			: 	"This page includes the details of sopping.",
	"cart.tbl.orderdate"			: 	"Order date",
	"cart.tbl.deliverydate"			: 	"Delivery date",
	"cart.tbl.cart"					: 	"Cart",
	"cart.tbl.item"					: 	"Item",
	"cart.tbl.amount"				: 	"Amount",
	"cart.tbl.status"				: 	"Status",
	"cart.tbl.ordernum"				: 	"Order Number",
	"cart.tbl.icon"					: 	"Icon",
	"cart.tbl.action"				: 	"Action",

	"addcart"									: 	"Add New Cart Entry",
	"editcart"									: 	"Edit Cart Entry",
	"placeholder.cart.orderdate"				: 	"Order Date",
	"placeholder.cart.deliverydate"				: 	"Delivery Date",
	"placeholder.cart.cart"						: 	"Cart",
	"placeholder.cart.item"						: 	"Item",
	"placeholder.cart.cartstatus"				: 	"Status",
	"placeholder.cart.amount"					: 	"Amount",
	"placeholder.cart.ordernum"					: 	"Ordernum",
	"placeholder.medicalbill.search.endmonth"	: 	"End Date",

	"validation.cart.field.orderdate"			: 	"Order Date should not be empty",
	"validation.cart.field.deliverydate"		: 	"Delivery Date should not be empty",
	"validation.cart.field.cart"				: 	"Cart should not be empty",
	"validation.cart.field.item"				: 	"Item should not be empty",
	"validation.cart.field.status"				: 	"Status should not be empty",
	"validation.cart.field.amount"				: 	"Amount should not be empty",
	"validation.cart.field.ordernum"			: 	"Order Number should not be empty",

// INSURANCE MANAGER SECTION
	"insurance.pageheader"					: 	"ഇൻഷുറൻസ് മാനേജർ",
	"insurance.tbl.name"					: 	"പേര്",
	"insurance.tbl.policyno"				: 	"പോളിസി നന്പർ",
	"insurance.tbl.sumassured"				: 	"സം അഷ്വേർഡ്",
	"insurance.tbl.startdate"				: 	"തുടങ്ങുന്ന ദിവസം",
	"insurance.tbl.maturitydate"			: 	"പൂർണതാ കാലാവധി",
	"insurance.tbl.policytype"				: 	"പോളിസി തരം",
	"insurance.tbl.premium"					: 	"പ്രീമിയം തുക",
	"insurance.tbl.nominee"					: 	"നോമിനീ",
	"insurance.tbl.nomineerelationship"		: 	"നോമിനീയുമായുള്ള ബന്ധം",
	"insurance.tbl.action"					: 	"നടപടി",
	"insurance.tbl.sno"						: 	"നിര",
	"insurance.tbl.comment"					: 	"അഭിപ്രായങ്ങൾ",
	"insurance.tbl.paiddate"				: 	"Paid Date",
	"insurance.tbl.amount"					: 	"Amount",
	"insurance.tbl.paymentmode"				: 	"Payment Mode",
	"addinsurance"							: 	"ഇൻഷ്വറൻസ് പോളിസി ചേർക്കുക",
	"editinsurance"							: 	"ഇൻഷുറൻസ് പോളിസി തിരുത്തുക",


	"placeholder.insurance.name"					: 	"ഇൻഷ്വർ ചെയ്തയാളുടെ പേര്",
	"placeholder.insurance.policy"					: 	"പോളിസി",
	"placeholder.insurance.sumassured"				: 	"സം അഷ്വേർഡ്",
	"placeholder.insurance.startdate"				: 	"തുടങ്ങുന്ന ദിവസം",
	"placeholder.insurance.maturitydate"			: 	"പൂർണതാ കാലാവധി",
	"placeholder.insurance.policytype"				: 	"പോളിസി തരം",
	"placeholder.insurance.premium"					: 	"പ്രീമിയം തുക",
	"placeholder.insurance.nominee"					: 	"നോമിനീ",
	"placeholder.insurance.nomineerelationship"		: 	"നോമിനീയുമായുള്ള ബന്ധം",
	"placeholder.insurance.comment"					: 	"അഭിപ്രായങ്ങൾ",

	"validation.insurance.name"						: 	"Name should not be empty",
	"validation.insurance.premium"					: 	"Premium should not be empty",
	"validation.insurance.policyno"					: 	"Policy Number should not be empty",
	"validation.insurance.policytype"				: 	"Policy Type should not be empty",
	"validation.insurance.sumassured"				: 	"Sum Assured should not be empty",
	"validation.insurance.startdate"				: 	"Start Date should not be empty",
	"validation.insurance.maturitydate"				: 	"Maturity Date should not be empty",
	"validation.insurance.nominee"					: 	"Nominee should not be empty",
	"validation.insurance.nomineerelationship"		: 	"Nominee Relationship should not be empty",

	"insurance.transaction.pageheader"							: 	"ഇൻഷുറൻസ് ഇടപാട്",
	"placeholder.insurance.transaction.pageheader"				: 	"Insurance Transaction",
	"placeholder.insurance.transaction.paymentmode"				: 	"Payment Mode",
	"placeholder.insurance.transaction.paiddate"				: 	"Paid Date",
	"placeholder.insurance.transaction.policyno"				: 	"Policy Number",
	"placeholder.insurance.transaction.amount"					: 	"Amount",
	"addinsurancetransaction"									: 	"Add Insurance Transaction",

	"validation.insurance.transaction.amount.required"				: 	"Transaction amount should not be empty",
	"validation.insurance.transaction.paiddate.required"			: 	"Paid date should not be empty",
	"validation.insurance.transaction.paymentmode.required"			: 	"Payment mode should not be empty",
	"validation.insurance.transaction.amount.numeric"				: 	"Transaction amount format is wrong",

	

// FLAT MANAGER SECTION
	"flat.pageheader"						:	"Flat Details",
	"flat.breadcrumb" 						: 	"Flat",
	"flat.tbl.icon"							:	"icon",
	"flat.title.address"					: 	"Flat Address",
	"flat.title.basicdetails"				: 	"Flat Basic Details",

	"flat.tbl.icon"							: 	"Icon",
	"flat.tbl.paiddate"						: 	"Paid Date",
	"flat.tbl.mode"							: 	"Payment Mode",
	"flat.tbl.chequeno"						: 	"Chequye No",
	"flat.tbl.mchno"						: 	"Managers Cheque No",
	"flat.tbl.ddno"							: 	"DD No",
	"flat.tbl.wire"							: 	"Wire Transfer",
	"flat.tbl.purpose"						: 	"Purpose",
	"flat.tbl.receiptno"					: 	"Receipt No",
	"flat.tbl.amount"						: 	"Amount",
	"flat.tbl.contactperson"				: 	"Contact Person",

	"label.flat.name"						: 	"Flat Name",
	"label.flat.contact1"					: 	"Contact Person 1",
	"label.flat.contact2"					: 	"Contact Person 2",
	"label.flat.bookeddate"					: 	"Booked Date",
	"label.flat.floor"						: 	"Floor",
	"label.flat.block"						: 	"Block",
	"label.flat.doornum"					: 	"Door Number",

	"placeholder.flat.wire"					: 	"Wire Transfer ID",
	"placeholder.flat.paymentMode"			: 	"Payment Mode",
	"placeholder.flat.mch"					: 	"Managers Cheque Number",
	"placeholder.flat.ch"					: 	"Cheque Number",
	"placeholder.flat.dd"					: 	"Demand Draft Number",
	"placeholder.flat.csh"					: 	"Cash",
	"placeholder.flat.paiddate"				: 	"Paid Date",
	"placeholder.flat.purpose"				: 	"Purpose",
	"placeholder.flat.receiptno"			: 	"Receipt Number",
	"placeholder.flat.contactperson"		: 	"Contact Person",
	"placeholder.flat.amount"				: 	"Amount",
	
	"addflatbasicpayment"					: 	"Add Static Payment Details",
	"editflatbasicpayment"					: 	"Edit Static Payment Details",


	"validation.flat.field.paymentmmode"	: 	"Payment Mode should not be Empty",
	"validation.flat.field.receiptstatus"	: 	"Payment Purpose should not be Empty",
	"validation.flat.field.amount"			: 	"Amount should not be Empty",
	"validation.flat.field.paiddate"		: 	"Paid Date should not be empty",
	

// CAR MANAGER SECTION
	"carmanager.pageheader"								: 	"Car Manager",
	"carmanager.tbl.car"								: 	"Car",
	"carmanager.tbl.filleddate"							: 	"Filled Date",
	"carmanager.tbl.amount"								: 	"Amount",
	"carmanager.tbl.action"								: 	"Action",
	"carmanager.tbl.servicestation"						: 	"Service Station",
	"carmanager.tbl.date"								: 	"Date",

	"carmanager.module.fuel"							: 	"Module: Fuel",
	"carmanager.module.service"							: 	"Module: Service",
	"carmanager.module.others"							: 	"Module: Others",

	"placeholder.carmanager.search.car"					: 	"Select Car",
	"placeholder.carmanager.search.carModuleType" 		: 	"Select Module",
	"placeholder.carmanager.fuel.filleddate"			: 	"Filled Date",
	"placeholder.carmanager.fuel.amount"				: 	"Amount",
	"placeholder.carmanager.fuel.car"					: 	"Which Car?",
	"placeholder.carmanager.fuel.comment"				: 	"Comment",
	"placeholder.carmanager.service.servicestation"		: 	"Service Station",
	"placeholder.carmanager.service.date"				: 	"Date",
	"placeholder.carmanager.others.item"				: 	"Item",

	"validation.carmanager.searchfield.car"				: 	"Car should not be empty",
	"validation.carmanager.searchfield.carModuleType"	: 	"Car module Type should not be empty",
	"validation.carmanager.fuel.filleddate"				: 	"Filled date should not be empty",
	"validation.carmanager.fuel.car"					: 	"Car model should not be empty",
	"validation.carmanager.fuel.amount"					: 	"Amount should not be empty",
	"validation.carmanager.service.servicestation"		: 	"Service Station should not be empty",
	"validation.carmanager.service.date"				: 	"Serviced Date should not be empty",
	"validation.carmanager.others.item"					: 	"Item should not be empty",

	"addfuel"											: 	"Add Fuel",
	"editfuel"											: 	"Edit Fuel",
	"addservice"										: 	"Add Service",
	"editservice"										: 	"Edit Service",
	"addothers"											: 	"Add Others",
	"editothers"										: 	"Edit Others"
	

	
	

	








}
