{
	"lbl.name":"Bijesh",
	"lbl.age":"Major",
	"login.btn.label" : "Login",
	"login.placeholder.passkey" : "Passkey",
	"login.failure.message" : "Entered wrong Passkey.",

	"menu.dashboard":"Dashboard1",
	"menu.travel":"Travel",
	"menu.mobile":"Mobile",
	"menu.internet":"Internet",
	"menu.houserent":"House Rent",
	"menu.ksfe":"KSFE",
	"menu.gas":"Gas",
	"menu.carservice":"Car Service",
	"menu.milk":"Milk",
	"menu.eb":"Electricty",

	"cnt.dashboard.pageheader":"This page shows the details of travel such as booked date, travel date, status of travel, mode of travel etc. Color of icon depicts the status of the travel. Red means Refund, Orange means Pending, Gray means Cancelled or Completed, Green means Open",
	"dashboard.pageheader":"Dashboard",
	"dashboard.tbl.contact":"Contact",
	"dashboard.tbl.amount":"Amount",
	"dashboard.tbl.edit":"Edit",
	"cnt.travel.pageheader":"This page shows the details of travel such as booked date, travel date, status of travel, mode of travel etc. Color of icon depicts the status of the travel. Red means Refund, Orange means Pending, Gray means Cancelled or Completed, Green means Open",
	"travel.pageheader":"Travel Details",
	"travel.breadcrumb" : "Travel",
	"travel.tbl.icon":"icon",
	"travel.tbl.source":"source",
	"travel.tbl.destination":"Destination",
	"travel.tbl.pnr":"pnr",
	"travel.tbl.traveldate":"travel date",
	"travel.tbl.bookeddate":"booked date",
	"travel.tbl.amount":"amount",
	"travel.tbl.action":"action",
	"cnt.rows":"Record:",
	"cnt.total":"Total:",
	"addtravel":"Add Travel Data",
	"edittravel":"Edit Travel Data",
	"breadcrumbMain":"aswa",
	"table.row.header":"records found",
	"travel.placeholder.travelstatus" : "Choose travel status",
	"travel.placeholder.travelicon" : "Choose travel mode",

	"rent.pageheader":"Rent Details",
	"rent.ll.pageheader":"Land Lord Details",
	"rent.breadcrumb" : "Rent",
	"rent.ll.breadcrumb" : "landlord",
	"cnt.rent.pageheader":"Shows rental details. Click on the landlord name to get the detailed rent view of that particular landlord. Click any of the icons from action coloumn to edit / delete / view the comment. Click on the add icon on the top rightside to add new data. <a href='#/ll/'>Click here to see the list of landlord</a>",
	"cnt.rent.ll.pageheader":"Shows rental details. Click on the landlord name to get the detailed rent view of that particular landlord. Click any of the icons from action coloumn to edit / delete / view the comment. Click on the add icon on the top rightside to add new data.",
	"cnt.rent.ll.details.pageheader":"Shows rental details. Click on the landlord name to get the detailed rent view of that particular landlord. Click any of the icons from action coloumn to edit / delete / view the comment. Click on the add icon on the top rightside to add new data. <a href='#/ll/'>Click here to see the list of landlord</a>",
	"rent.tbl.icon" : "icon",
	"rent.tbl.month" : "month",
	"rent.tbl.amount" : "amount",
	"rent.tbl.landlord" : "landlord",
	"rent.tbl.comment" : "comment",
	"rent.tbl.action" : "action",
	"rent.tbl.receipt"	:	"Receipt",
	"addrent":"Add Rent Data",
	"rent.details.rentview" : "Rent table",
	"rent.placeholder.landlord" : "Choose Landlord",
	"rent.placeholder.rentstatus" : "Choose status",
	"editrent":"Edit Rent Data",

	"gas.pageheader":"Gas Details",
	"gas.breadcrumb" : "gas",
	"cnt.gas.details.pageheader" : "Page shows the detailed view of cooking gas consumption. Sub status green is <u>amount transferred to bank account</u>, red is <u>amount not yet transferred to bank account</u>. Order status red is <u>not yet delivered</u> and green is <u>delivered</u>.",
	"gas.tbl.bill"	:	"bill",
	"gas.tbl.orderdate"	:	"Order Date",
	"gas.tbl.delivereddate"	:	"Deli-Date",
	"gas.tbl.orderstatus"	:	"status",
	"gas.tbl.amountpaid"	:	"paid",
	"gas.tbl.subamount"	:	"subsidey",
	"gas.tbl.substatus"	:	"sub-status",


	"tbl.label.showmore" : "Show more",
	"tbl.label.showless" : "Show less",

	"modal.update.title" : "updated",
	"modal.update.message"	:	"Data updated successfully!",
	"modal.add.title" : "added",
	"modal.add.message"	:	"Data added successfully!",

	"filter.placeholder.filterstatus" : "- Select status -",
	"filter.placeholder.landlordname" : "- Select landlord -",
	"tooltip.edit" : "Edit",
	"tooltip.add" : "Add",
	"tooltip.trash" : "Trash",
	"tooltip.comment" : "Comment",
	"generalinfo.one" : "Facility is not available at this moment. Visit again later"



}
