Messages = {
	
	"lbl.name"						:	"Bijesh",
	"lbl.age"						:	"Major",
	"lbl.comment"					: 	"Comment",					
	"login.btn.label" 				: 	"Login",
	"login.placeholder.passkey" 	: 	"Passkey",
	"login.failure.message" 		: 	"Entered wrong Passkey.",
	"btn.clear"						: 	"Clear",
	"btn.search"					: 	"Search",

	"menu.dashboard"				:	"Dashboard",
	"menu.travel"					:	"Travel",
	"menu.mobile"					:	"Mobile",
	"menu.internet"					:	"Internet",
	"menu.houserent"				:	"House Rent",
	"menu.ksfe"						:	"KSFE",
	"menu.gas"						:	"Gas",
	"menu.carservice"				:	"Car Service",
	"menu.milk"						:	"Milk",
	"menu.eb"						:	"Electricty",
	"menu.passkey-reset"			:	"Reset Passkey",
	"menu.logout"					:	"Logout",
	"menu.medicalbill"				:	"Medicalbill",
	"menu.cart"						:	"Shopping Cart",
	"menu.money"					:	"Money",

	"dashboard.pageheader"					:	"Dashboard",
	"dashboard.tbl.contact"					:	"Contact",
	"dashboard.tbl.amount"					:	"Amount",
	"dashboard.tbl.edit"					:	"Edit",
	"dashboard.title.iowe"					:	"I Owe",
	"dashboard.title.iowesme"				:	"Who Owes Me",
	"dashboard.title.billreminders"			:	"Bill Reminders",
	"dashboard.tbl.billitem"				:	"Bill Item",
	"dashboard.tbl.billdate"				:	"Bill Date",
	"dashboard.tbl.totalitem"				:	"Particulars",
	"dashboard.title.mobilechart"			:	"Mobile Chart",
	"dashboard.title.Totals"				:	"Grand Totals",

	"grandtotal.label.rent"					:	"Flat / Appartment Rent",
	"grandtotal.label.mobile"				:	"Mobile bill (husband and wife)",
	"grandtotal.label.gas"					:	"Home Gas (Post Subsidey)",
	"grandtotal.label.net"					:	"Broadband Connection",
	"grandtotal.label.eb"					:	"Electricity Charge",

	"travel.pageheader"						:	"Travel Details",
	"travel.breadcrumb" 					: 	"Travel",
	"travel.tbl.icon"						:	"icon",
	"travel.tbl.source"						:	"source",
	"travel.tbl.destination"				:	"Destination",
	"travel.tbl.pnr"						:	"pnr",
	"travel.tbl.traveldate"					:	"travel date",
	"travel.tbl.bookeddate"					:	"booked date",
	"travel.tbl.amount"						:	"amount",
	"travel.tbl.action"						:	"action",
	"cnt.rows"								:	"Record : ",
	"cnt.total"								:  	"Total Amount : ",
	"addtravel"								:	"Add Travel Data",
	"edittravel"							:	"Edit Travel Data",
	"breadcrumbMain"						:	"aswa",
	"table.row.header"						:	"records found",
	"travel.placeholder.travelstatus" 		: 	"Choose travel status",
	"travel.placeholder.travelicon" 		: 	"Choose travel mode",

	"rent.pageheader"						:	"Rent Details",
	"rent.ll.pageheader"					:	"Land Lord Details",
	"rent.breadcrumb" 						: 	"Rent",
	"rent.ll.breadcrumb" 					: 	"landlord",


	"ksfe.pageheader"					:	"KSFE",
	"ksfe.tbl.month"					:	"Month",
	"ksfe.tbl.amount"					:	"Amount",
	"ksfe.tbl.status"					:	"Status",
	"ksfe.tbl.comment"					:	"Comments",

	"mobile.pageheader"					: 	"Mobile Bill",
	"mobile.tbl.icon"					: 	"ICON",
	"mobile.tbl.billmonth"				: 	"Bill Month",
	"mobile.tbl.billno"					: 	"Bill No",
	"mobile.tbl.amount"					: 	"Amount",
	"mobile.tbl.user"					: 	"User",
	"mobile.tbl.action"					: 	"Action",
	"addmobile"							: 	"Add New Mobile Entry",
	"placeholder.mobile.billmonth"		: 	"Bill Month",
	"placeholder.mobile.user"			: 	"User",
	"placeholder.mobile.amount"			: 	"Amount",
	"placeholder.mobile.billno"			: 	"Bill no",

	"validation.mobile.field.month"		: 	"Bill month should not be empty",
	"validation.mobile.field.billno"	: 	"Bill number should not be empty",
	"validation.mobile.field.amount"	: 	"Bill amount should not be empty",
	"validation.mobile.field.user"		: 	"Mobile user should not be empty",
	"validation.mobile.field.comment"	: 	"Comment should not be empty",



	"medicalbill.pageheader"						: 	"Medical Bill",
	"medicalbill.tbl.icon"							: 	"ICON",
	"medicalbill.tbl.billmonth"						: 	"Bill Month",
	"medicalbill.tbl.billno"						: 	"Bill No",
	"medicalbill.tbl.billtype"						: 	"Bill Type",
	"medicalbill.tbl.amount"						: 	"Amount",
	"medicalbill.tbl.user"							: 	"User",
	"medicalbill.tbl.action"						: 	"Action",
	"addmedicalbill"								: 	"Add New Mobile Entry",
	"placeholder.medicalbill.billmonth"				: 	"Bill Month",
	"placeholder.medicalbill.user"					: 	"User",
	"placeholder.medicalbill.amount"				: 	"Amount",
	"placeholder.medicalbill.billno"				: 	"Bill no",
	"placeholder.medicalbill.type"					: 	"Bill Type",
	"placeholder.medicalbill.search.startmonth"		: 	"Start Date",
	"placeholder.medicalbill.search.endmonth"		: 	"End Date",

	"validation.medicalbill.field.month"	: 	"Bill month should not be empty",
	"validation.medicalbill.field.billno"	: 	"Bill number should not be empty",
	"validation.medicalbill.field.amount"	: 	"Bill amount should not be empty",
	"validation.medicalbill.field.user"		: 	"Mobile user should not be empty",
	"validation.medicalbill.field.comment"	: 	"Comment should not be empty",



	"cnt.rent.pageheader"				:	"Shows rental details. Click on the landlord name to get the detailed rent view of that particular landlord. Click any of the icons from action coloumn to edit / delete / view the comment. Click on the add icon on the top rightside to add new data. <a href='#/ll/'>Click here to see the list of landlord</a>",
	"cnt.rent.ll.pageheader"			:	"Shows rental details. Click on the landlord name to get the detailed rent view of that particular landlord. Click any of the icons from action coloumn to edit / delete / view the comment. Click on the add icon on the top rightside to add new data.",
	"cnt.rent.ll.details.pageheader"	:	"Shows rental details. Click on the landlord name to get the detailed rent view of that particular landlord. Click any of the icons from action coloumn to edit / delete / view the comment. Click on the add icon on the top rightside to add new data. <a href='#/ll/'>Click here to see the list of landlord</a>",
	"cnt.gas.details.pageheader" 		: 	"Page shows the detailed view of cooking gas consumption. Sub status green is <u>amount transferred to bank account</u>, red is <u>amount not yet transferred to bank account</u>. Order status red is <u>not yet delivered</u> and green is <u>delivered</u>.",
	"cnt.travel.pageheader"				:	"This page shows the details of travel such as booked date, travel date, status of travel, mode of travel etc. Color of icon depicts the status of the travel. Red means Refund, Orange means Pending, Gray means Cancelled or Completed, Green means Open",
	"cnt.dashboard.pageheader"			:	"This page shows the details of travel such as booked date, travel date, status of travel, mode of travel etc. Color of icon depicts the status of the travel. Red means Refund, Orange means Pending, Gray means Cancelled or Completed, Green means Open",
	"cnt.ksfe.pageheader"				:	"It is a unique financial product, which blends the advantages of both investment and advance. It is a risk free safe haven for the public as KSFE conducts only chitties fully governed by the provisions of Central Chit Fund Act 1982",
	"cnt.medicalbill.pageheader"		: 	"Medical bill tax service section.",


	"rent.tbl.icon" 				: 	"icon",
	"rent.tbl.month" 				: 	"month",
	"rent.tbl.amount" 				: 	"amount",
	"rent.tbl.landlord" 			: 	"landlord",
	"rent.tbl.comment" 				: 	"comment",
	"rent.tbl.action" 				: 	"action",
	"rent.tbl.receipt"				:	"Receipt",
	"rent.tbl.tootip.clickhere" 	: 	"Click here for detailed view",
	"rent.placeholder.landlord" 	: 	"Choose Landlord",
	"rent.placeholder.rentstatus" 	: 	"Choose status",
	"rent.placeholder.receipt"		: 	"Choose Receipt Status", 
	"rent.placeholder.status"		: 	"Status",
	"rent.placeholder.lltype" 	: 	"Landlord Type",
	"editrent"						:	"Edit Rent Data",
	"rent.ll.edit.title"			: 	"Edit Landlord",
	"rent.ll.add.title"				: 	"Add Landlord",
	"label.rent.totalAmount"		: 	"Total Amount :",
	"label.rent.dop"				: 	"DOP :",
	"label.rent.contact"			: 	"Contact :",
	"label.rent.address"			: 	"Address :",
	"label.rent.comment"			: 	"Comment :",
	"label.rent.link.renttable"		: 	"Rent Table",
	"label.rent.link.landlord"		: 	"Landlord",
	"label.rent.dov"				: 	"DOV :",
	"label.rent.pan"				: 	"PAN :",
	"label.rent.advance"			: 	"Advance :",
	"validation.ll.field.pan"		: 	"Pan is mandatory",
	"validation.ll.field.dop"		: 	"DOP is mandatory",
	"validation.ll.field.dov"		: 	"DOV is mandatory",
	"validation.ll.field.advance"	: 	"Advance is mandatory",
	"validation.ll.field.name"		: 	"Name is mandatory",
	"validation.ll.field.status"	: 	"Status is mandatory",
	"validation.ll.field.contact"	: 	"Contact is mandatory",
	"validation.ll.field.address"	: 	"Address is mandatory",
	"validation.ll.field.comment"	: 	"Comment is mandatory",

	"placeholder.rent.dop"					: 	"DOP",
	"placeholder.rent.dov"					: 	"DOV",
	"placeholder.rent.pan"					: 	"PAN",
	"placeholder.rent.advanceamount"		: 	"Advance Amount",
	"placeholder.rent.contact"				: 	"Contact",
	"placeholder.rent.name"					: 	"Name",

	"gas.pageheader"				:	"Gas Details",
	"gas.breadcrumb" 				: 	"Gas",
	"gas.tbl.bill"					:	"bill",
	"gas.tbl.orderdate"				:	"Order Date",
	"gas.tbl.delivereddate"			:	"Deli-Date",
	"gas.tbl.orderstatus"			:	"status",
	"gas.tbl.amountpaid"			:	"paid",
	"gas.tbl.subamount"				:	"subsidey",
	"gas.tbl.substatus"				:	"sub-status",

	"tbl.label.showmore" 	: 	"Show more",
	"tbl.label.showless" 	: 	"Show less",

	"modal.update.title" 		: 	"updated",
	"modal.update.message"		:	"Data updated successfully!",
	"modal.add.title" 			: 	"added",
	"modal.add.message"			:	"Data added successfully!",

	"validation.field.notempty"					:	"Field(s) should not be empty",
	"validation.br.field.item"					:	"Item should not be empty",
	"validation.br.field.amount"				:	"Amount should not be empty",
	"validation.br.field.billdate"				:	"Billdate should not be empty",
	"validation.br.field.status"				:	"Status should not be empty",

	"validation.iowe.field.contact"			:	"To whome should not be empty",
	"validation.iowe.field.amount"			:	"Amount should not be empty",
	"validation.iowe.field.owedate"			:	"I Owe date should not be empty",
	"validation.iowe.field.status"			:	"Status should not be empty",
	"validation.iowe.field.category"		:	"Category should not be empty",

	"cart.pageheader"				: 	"Shopping Cart",
	"cnt.cart.pageheader"			: 	"This page includes the details of sopping.",
	"cart.tbl.orderdate"			: 	"Order date",
	"cart.tbl.deliverydate"			: 	"Delivery date",
	"cart.tbl.cart"					: 	"Cart",
	"cart.tbl.item"					: 	"Item",
	"cart.tbl.amount"				: 	"Amount",
	"cart.tbl.status"				: 	"Status",
	"cart.tbl.ordernum"				: 	"Order Number",
	"cart.tbl.icon"					: 	"Icon",
	"cart.tbl.action"				: 	"Action",

	"addcart"									: 	"Add New Cart Entry",
	"editcart"									: 	"Edit Cart Entry",
	"placeholder.cart.orderdate"				: 	"Order Date",
	"placeholder.cart.deliverydate"				: 	"Delivery Date",
	"placeholder.cart.cart"						: 	"Cart",
	"placeholder.cart.item"						: 	"Item",
	"placeholder.cart.cartstatus"				: 	"Status",
	"placeholder.cart.amount"					: 	"Amount",
	"placeholder.cart.ordernum"					: 	"Ordernum",
	"placeholder.medicalbill.search.endmonth"	: 	"End Date",

	"validation.cart.field.orderdate"			: 	"Order Date should not be empty",
	"validation.cart.field.deliverydate"		: 	"Delivery Date should not be empty",
	"validation.cart.field.cart"				: 	"Cart should not be empty",
	"validation.cart.field.item"				: 	"Item should not be empty",
	"validation.cart.field.status"				: 	"Status should not be empty",
	"validation.cart.field.amount"				: 	"Amount should not be empty",
	"validation.cart.field.ordernum"			: 	"Order Number should not be empty",


	"filter.placeholder.filterstatus" 	: "- Select status -",
	"filter.placeholder.landlordname" 	: "- Select landlord -",

	"tooltip.edit" 			: 	"Edit",
	"tooltip.add" 			: 	"Add",
	"tooltip.trash" 		: 	"Trash",
	"tooltip.comment"		: 	"Comment",
	"tooltip.refresh"		:	"Refresh",

	"generalinfo.one" : "Facility is not available at this moment. Visit again later",

	"br.edit.placeholder.item"			:	"Item",
	"br.edit.placeholder.amount"		:	"Amount",
	"br.edit.placeholder.billdate"		:	"Bill Date",
	"br.edit.placeholder.status"		:	"- Select status -",

	"iowe.edit.placeholder.contact"			:	"To Whome",
	"iowe.edit.placeholder.amount"			:	"Amount",
	"iowe.edit.placeholder.owedate"			:	"I Owe Date",
	"iowe.edit.placeholder.paiddate"		:	"Paid Date",
	"iowe.edit.placeholder.status"			:	"- Select status -",
	"iowe.edit.placeholder.category"		:	"- Select category -",

	"addbr"					:	"Add Bill Reminder",
	"editbr"				:	"Edit Bill Reminder",
	"addrent"				:	"Add Rent Data",
	"addiowe"				:	"Add I Owe Data",
	"editiowe"				:	"Edit I Owe Data",

	"travel.edit.form.confirmation.title"		: 	"Travel edit confirmation check",
	"travel.edit.form.confirmation.body"		: 	"There are some data updated in the CRUD form. Please check it or press YES to close the Wwindow"
}
